// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.0
// source: speedmimi.proto

package proto

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

import (
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// 消息定义

type Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Server   *ServerConfig             `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Ssl      *SSLConfig                `protobuf:"bytes,2,opt,name=ssl,proto3" json:"ssl,omitempty"`
	Backends map[string]*BackendList   `protobuf:"bytes,3,rep,name=backends,proto3" json:"backends,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Routing  map[string]*RoutingRule   `protobuf:"bytes,4,rep,name=routing,proto3" json:"routing,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Grpc     *GRPCConfig               `protobuf:"bytes,5,opt,name=grpc,proto3" json:"grpc,omitempty"`
}

func (x *Config) Reset() {
	*x = Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_speedmimi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_speedmimi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_speedmimi_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetServer() *ServerConfig {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Config) GetSsl() *SSLConfig {
	if x != nil {
		return x.Ssl
	}
	return nil
}

func (x *Config) GetBackends() map[string]*BackendList {
	if x != nil {
		return x.Backends
	}
	return nil
}

func (x *Config) GetRouting() map[string]*RoutingRule {
	if x != nil {
		return x.Routing
	}
	return nil
}

func (x *Config) GetGrpc() *GRPCConfig {
	if x != nil {
		return x.Grpc
	}
	return nil
}

type ServerConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Host          string   `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	ReadTimeout   string   `protobuf:"bytes,3,opt,name=read_timeout,json=readTimeout,proto3" json:"read_timeout,omitempty"`
	WriteTimeout  string   `protobuf:"bytes,4,opt,name=write_timeout,json=writeTimeout,proto3" json:"write_timeout,omitempty"`
	MaxConn       int32    `protobuf:"varint,5,opt,name=max_conn,json=maxConn,proto3" json:"max_conn,omitempty"`
	RealIpHeader  string   `protobuf:"bytes,6,opt,name=real_ip_header,json=realIpHeader,proto3" json:"real_ip_header,omitempty"`
	TrustedProxies []string `protobuf:"bytes,7,rep,name=trusted_proxies,json=trustedProxies,proto3" json:"trusted_proxies,omitempty"`
}

func (x *ServerConfig) Reset() {
	*x = ServerConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_speedmimi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfig) ProtoMessage() {}

func (x *ServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_speedmimi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConfig.ProtoReflect.Descriptor instead.
func (*ServerConfig) Descriptor() ([]byte, []int) {
	return file_speedmimi_proto_rawDescGZIP(), []int{1}
}

func (x *ServerConfig) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *ServerConfig) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServerConfig) GetReadTimeout() string {
	if x != nil {
		return x.ReadTimeout
	}
	return ""
}

func (x *ServerConfig) GetWriteTimeout() string {
	if x != nil {
		return x.WriteTimeout
	}
	return ""
}

func (x *ServerConfig) GetMaxConn() int32 {
	if x != nil {
		return x.MaxConn
	}
	return 0
}

func (x *ServerConfig) GetRealIpHeader() string {
	if x != nil {
		return x.RealIpHeader
	}
	return ""
}

func (x *ServerConfig) GetTrustedProxies() []string {
	if x != nil {
		return x.TrustedProxies
	}
	return nil
}

type SSLConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enabled  bool   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CertFile string `protobuf:"bytes,2,opt,name=cert_file,json=certFile,proto3" json:"cert_file,omitempty"`
	KeyFile  string `protobuf:"bytes,3,opt,name=key_file,json=keyFile,proto3" json:"key_file,omitempty"`
}

func (x *SSLConfig) Reset() {
	*x = SSLConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_speedmimi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SSLConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SSLConfig) ProtoMessage() {}

func (x *SSLConfig) ProtoReflect() protoreflect.Message {
	mi := &file_speedmimi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SSLConfig.ProtoReflect.Descriptor instead.
func (*SSLConfig) Descriptor() ([]byte, []int) {
	return file_speedmimi_proto_rawDescGZIP(), []int{2}
}

func (x *SSLConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *SSLConfig) GetCertFile() string {
	if x != nil {
		return x.CertFile
	}
	return ""
}

func (x *SSLConfig) GetKeyFile() string {
	if x != nil {
		return x.KeyFile
	}
	return ""
}

type BackendList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Backends []*Backend `protobuf:"bytes,1,rep,name=backends,proto3" json:"backends,omitempty"`
}

func (x *BackendList) Reset() {
	*x = BackendList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_speedmimi_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackendList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendList) ProtoMessage() {}

func (x *BackendList) ProtoReflect() protoreflect.Message {
	mi := &file_speedmimi_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendList.ProtoReflect.Descriptor instead.
func (*BackendList) Descriptor() ([]byte, []int) {
	return file_speedmimi_proto_rawDescGZIP(), []int{3}
}

func (x *BackendList) GetBackends() []*Backend {
	if x != nil {
		return x.Backends
	}
	return nil
}

type Backend struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name         string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Host         string          `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Port         int32           `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Weight       int32           `protobuf:"varint,5,opt,name=weight,proto3" json:"weight,omitempty"`
	Scheme       string          `protobuf:"bytes,6,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Active       bool            `protobuf:"varint,7,opt,name=active,proto3" json:"active,omitempty"`
	MaxConn      int32           `protobuf:"varint,8,opt,name=max_conn,json=maxConn,proto3" json:"max_conn,omitempty"`
	HealthCheck  *HealthCheck    `protobuf:"bytes,9,opt,name=health_check,json=healthCheck,proto3" json:"health_check,omitempty"`
	Performance  *PerformanceInfo `protobuf:"bytes,10,opt,name=performance,proto3" json:"performance,omitempty"`
	LastReport   int64           `protobuf:"varint,11,opt,name=last_report,json=lastReport,proto3" json:"last_report,omitempty"`
	Connections  int64           `protobuf:"varint,12,opt,name=connections,proto3" json:"connections,omitempty"`
}

func (x *Backend) Reset() {
	*x = Backend{}
	if protoimpl.UnsafeEnabled {
		mi := &file_speedmimi_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Backend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Backend) ProtoMessage() {}

func (x *Backend) ProtoReflect() protoreflect.Message {
	mi := &file_speedmimi_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Backend.ProtoReflect.Descriptor instead.
func (*Backend) Descriptor() ([]byte, []int) {
	return file_speedmimi_proto_rawDescGZIP(), []int{4}
}

func (x *Backend) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Backend) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Backend) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Backend) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Backend) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Backend) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *Backend) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *Backend) GetMaxConn() int32 {
	if x != nil {
		return x.MaxConn
	}
	return 0
}

func (x *Backend) GetHealthCheck() *HealthCheck {
	if x != nil {
		return x.HealthCheck
	}
	return nil
}

func (x *Backend) GetPerformance() *PerformanceInfo {
	if x != nil {
		return x.Performance
	}
	return nil
}

func (x *Backend) GetLastReport() int64 {
	if x != nil {
		return x.LastReport
	}
	return 0
}

func (x *Backend) GetConnections() int64 {
	if x != nil {
		return x.Connections
	}
	return 0
}

type HealthCheck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path     string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Interval string `protobuf:"bytes,2,opt,name=interval,proto3" json:"interval,omitempty"`
	Timeout  string `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Failures int32  `protobuf:"varint,4,opt,name=failures,proto3" json:"failures,omitempty"`
}

func (x *HealthCheck) Reset() {
	*x = HealthCheck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_speedmimi_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HealthCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheck) ProtoMessage() {}

func (x *HealthCheck) ProtoReflect() protoreflect.Message {
	mi := &file_speedmimi_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheck.ProtoReflect.Descriptor instead.
func (*HealthCheck) Descriptor() ([]byte, []int) {
	return file_speedmimi_proto_rawDescGZIP(), []int{5}
}

func (x *HealthCheck) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HealthCheck) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *HealthCheck) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

func (x *HealthCheck) GetFailures() int32 {
	if x != nil {
		return x.Failures
	}
	return 0
}

type RoutingRule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path       string            `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Upstream   string            `protobuf:"bytes,2,opt,name=upstream,proto3" json:"upstream,omitempty"`
	LoadBalancer string          `protobuf:"bytes,3,opt,name=load_balancer,json=loadBalancer,proto3" json:"load_balancer,omitempty"`
	Protocols  map[string]string `protobuf:"bytes,4,rep,name=protocols,proto3" json:"protocols,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *RoutingRule) Reset() {
	*x = RoutingRule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_speedmimi_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoutingRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutingRule) ProtoMessage() {}

func (x *RoutingRule) ProtoReflect() protoreflect.Message {
	mi := &file_speedmimi_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutingRule.ProtoReflect.Descriptor instead.
func (*RoutingRule) Descriptor() ([]byte, []int) {
	return file_speedmimi_proto_rawDescGZIP(), []int{6}
}

func (x *RoutingRule) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RoutingRule) GetUpstream() string {
	if x != nil {
		return x.Upstream
	}
	return ""
}

func (x *RoutingRule) GetLoadBalancer() string {
	if x != nil {
		return x.LoadBalancer
	}
	return ""
}

func (x *RoutingRule) GetProtocols() map[string]string {
	if x != nil {
		return x.Protocols
	}
	return nil
}

type GRPCConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enabled bool   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Host    string `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port    int32  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *GRPCConfig) Reset() {
	*x = GRPCConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_speedmimi_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GRPCConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GRPCConfig) ProtoMessage() {}

func (x *GRPCConfig) ProtoReflect() protoreflect.Message {
	mi := &file_speedmimi_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GRPCConfig.ProtoReflect.Descriptor instead.
func (*GRPCConfig) Descriptor() ([]byte, []int) {
	return file_speedmimi_proto_rawDescGZIP(), []int{7}
}

func (x *GRPCConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *GRPCConfig) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *GRPCConfig) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type PerformanceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CpuUsage    float64 `protobuf:"fixed64,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage float64 `protobuf:"fixed64,2,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	DiskUsage   float64 `protobuf:"fixed64,3,opt,name=disk_usage,json=diskUsage,proto3" json:"disk_usage,omitempty"`
	LoadAvg_1   float64 `protobuf:"fixed64,4,opt,name=load_avg_1,json=loadAvg1,proto3" json:"load_avg_1,omitempty"`
	LoadAvg_5   float64 `protobuf:"fixed64,5,opt,name=load_avg_5,json=loadAvg5,proto3" json:"load_avg_5,omitempty"`
	LoadAvg_15  float64 `protobuf:"fixed64,6,opt,name=load_avg_15,json=loadAvg15,proto3" json:"load_avg_15,omitempty"`
	NetworkIn   float64 `protobuf:"fixed64,7,opt,name=network_in,json=networkIn,proto3" json:"network_in,omitempty"`
	NetworkOut  float64 `protobuf:"fixed64,8,opt,name=network_out,json=networkOut,proto3" json:"network_out,omitempty"`
	Timestamp   int64   `protobuf:"varint,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *PerformanceInfo) Reset() {
	*x = PerformanceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_speedmimi_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PerformanceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerformanceInfo) ProtoMessage() {}

func (x *PerformanceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_speedmimi_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerformanceInfo.ProtoReflect.Descriptor instead.
func (*PerformanceInfo) Descriptor() ([]byte, []int) {
	return file_speedmimi_proto_rawDescGZIP(), []int{8}
}

func (x *PerformanceInfo) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *PerformanceInfo) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *PerformanceInfo) GetDiskUsage() float64 {
	if x != nil {
		return x.DiskUsage
	}
	return 0
}

func (x *PerformanceInfo) GetLoadAvg_1() float64 {
	if x != nil {
		return x.LoadAvg_1
	}
	return 0
}

func (x *PerformanceInfo) GetLoadAvg_5() float64 {
	if x != nil {
		return x.LoadAvg_5
	}
	return 0
}

func (x *PerformanceInfo) GetLoadAvg_15() float64 {
	if x != nil {
		return x.LoadAvg_15
	}
	return 0
}

func (x *PerformanceInfo) GetNetworkIn() float64 {
	if x != nil {
		return x.NetworkIn
	}
	return 0
}

func (x *PerformanceInfo) GetNetworkOut() float64 {
	if x != nil {
		return x.NetworkOut
	}
	return 0
}

func (x *PerformanceInfo) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// 请求响应消息定义

type UpdateConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config *Config `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *UpdateConfigRequest) Reset() {
	*x = UpdateConfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_speedmimi_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigRequest) ProtoMessage() {}

func (x *UpdateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_speedmimi_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateConfigRequest) Descriptor() ([]byte, []int) {
	return file_speedmimi_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateConfigRequest) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

type UpdateConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *UpdateConfigResponse) Reset() {
	*x = UpdateConfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_speedmimi_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigResponse) ProtoMessage() {}

func (x *UpdateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_speedmimi_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateConfigResponse) Descriptor() ([]byte, []int) {
	return file_speedmimi_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Config *Config `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_speedmimi_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_speedmimi_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_speedmimi_proto_rawDescGZIP(), []int{11}
}

func (x *GetConfigResponse) GetConfig() *Config {
	if x != nil {
		return x.Config
	}
	return nil
}

type ReloadSSLResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ReloadSSLResponse) Reset() {
	*x = ReloadSSLResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_speedmimi_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReloadSSLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadSSLResponse) ProtoMessage() {}

func (x *ReloadSSLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_speedmimi_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadSSLResponse.ProtoReflect.Descriptor instead.
func (*ReloadSSLResponse) Descriptor() ([]byte, []int) {
	return file_speedmimi_proto_rawDescGZIP(), []int{12}
}

func (x *ReloadSSLResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReloadSSLResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetBackendsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Upstream string `protobuf:"bytes,1,opt,name=upstream,proto3" json:"upstream,omitempty"`
}

func (x *GetBackendsRequest) Reset() {
	*x = GetBackendsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_speedmimi_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBackendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackendsRequest) ProtoMessage() {}

func (x *GetBackendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_speedmimi_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBackendsRequest.ProtoReflect.Descriptor instead.
func (*GetBackendsRequest) Descriptor() ([]byte, []int) {
	return file_speedmimi_proto_rawDescGZIP(), []int{13}
}

func (x *GetBackendsRequest) GetUpstream() string {
	if x != nil {
		return x.Upstream
	}
	return ""
}

type GetBackendsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Backends []*Backend `protobuf:"bytes,1,rep,name=backends,proto3" json:"backends,omitempty"`
}

func (x *GetBackendsResponse) Reset() {
	*x = GetBackendsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_speedmimi_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBackendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackendsResponse) ProtoMessage() {}

func (x *GetBackendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_speedmimi_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBackendsResponse.ProtoReflect.Descriptor instead.
func (*GetBackendsResponse) Descriptor() ([]byte, []int) {
	return file_speedmimi_proto_rawDescGZIP(), []int{14}
}

func (x *GetBackendsResponse) GetBackends() []*Backend {
	if x != nil {
		return x.Backends
	}
	return nil
}

type AddBackendRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Upstream string   `protobuf:"bytes,1,opt,name=upstream,proto3" json:"upstream,omitempty"`
	Backend  *Backend `protobuf:"bytes,2,opt,name=backend,proto3" json:"backend,omitempty"`
}

func (x *AddBackendRequest) Reset() {
	*x = AddBackendRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_speedmimi_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddBackendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBackendRequest) ProtoMessage() {}

func (x *AddBackendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_speedmimi_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBackendRequest.ProtoReflect.Descriptor instead.
func (*AddBackendRequest) Descriptor() ([]byte, []int) {
	return file_speedmimi_proto_rawDescGZIP(), []int{15}
}

func (x *AddBackendRequest) GetUpstream() string {
	if x != nil {
		return x.Upstream
	}
	return ""
}

func (x *AddBackendRequest) GetBackend() *Backend {
	if x != nil {
		return x.Backend
	}
	return nil
}

type AddBackendResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *AddBackendResponse) Reset() {
	*x = AddBackendResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_speedmimi_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddBackendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBackendResponse) ProtoMessage() {}

func (x *AddBackendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_speedmimi_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBackendResponse.ProtoReflect.Descriptor instead.
func (*AddBackendResponse) Descriptor() ([]byte, []int) {
	return file_speedmimi_proto_rawDescGZIP(), []int{16}
}

func (x *AddBackendResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddBackendResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RemoveBackendRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Upstream   string `protobuf:"bytes,1,opt,name=upstream,proto3" json:"upstream,omitempty"`
	BackendId string `protobuf:"bytes,2,opt,name=backend_id,json=backendId,proto3" json:"backend_id,omitempty"`
}

func (x *RemoveBackendRequest) Reset() {
	*x = RemoveBackendRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_speedmimi_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveBackendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBackendRequest) ProtoMessage() {}

func (x *RemoveBackendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_speedmimi_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBackendRequest.ProtoReflect.Descriptor instead.
func (*RemoveBackendRequest) Descriptor() ([]byte, []int) {
	return file_speedmimi_proto_rawDescGZIP(), []int{17}
}

func (x *RemoveBackendRequest) GetUpstream() string {
	if x != nil {
		return x.Upstream
	}
	return ""
}

func (x *RemoveBackendRequest) GetBackendId() string {
	if x != nil {
		return x.BackendId
	}
	return ""
}

type RemoveBackendResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *RemoveBackendResponse) Reset() {
	*x = RemoveBackendResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_speedmimi_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveBackendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBackendResponse) ProtoMessage() {}

func (x *RemoveBackendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_speedmimi_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBackendResponse.ProtoReflect.Descriptor instead.
func (*RemoveBackendResponse) Descriptor() ([]byte, []int) {
	return file_speedmimi_proto_rawDescGZIP(), []int{18}
}

func (x *RemoveBackendResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveBackendResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateBackendRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Upstream string   `protobuf:"bytes,1,opt,name=upstream,proto3" json:"upstream,omitempty"`
	Backend  *Backend `protobuf:"bytes,2,opt,name=backend,proto3" json:"backend,omitempty"`
}

func (x *UpdateBackendRequest) Reset() {
	*x = UpdateBackendRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_speedmimi_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBackendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBackendRequest) ProtoMessage() {}

func (x *UpdateBackendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_speedmimi_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBackendRequest.ProtoReflect.Descriptor instead.
func (*UpdateBackendRequest) Descriptor() ([]byte, []int) {
	return file_speedmimi_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateBackendRequest) GetUpstream() string {
	if x != nil {
		return x.Upstream
	}
	return ""
}

func (x *UpdateBackendRequest) GetBackend() *Backend {
	if x != nil {
		return x.Backend
	}
	return nil
}

type UpdateBackendResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *UpdateBackendResponse) Reset() {
	*x = UpdateBackendResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_speedmimi_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBackendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBackendResponse) ProtoMessage() {}

func (x *UpdateBackendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_speedmimi_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBackendResponse.ProtoReflect.Descriptor instead.
func (*UpdateBackendResponse) Descriptor() ([]byte, []int) {
	return file_speedmimi_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateBackendResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateBackendResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DisconnectBackendRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Upstream   string `protobuf:"bytes,1,opt,name=upstream,proto3" json:"upstream,omitempty"`
	BackendId string `protobuf:"bytes,2,opt,name=backend_id,json=backendId,proto3" json:"backend_id,omitempty"`
}

func (x *DisconnectBackendRequest) Reset() {
	*x = DisconnectBackendRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_speedmimi_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisconnectBackendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectBackendRequest) ProtoMessage() {}

func (x *DisconnectBackendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_speedmimi_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectBackendRequest.ProtoReflect.Descriptor instead.
func (*DisconnectBackendRequest) Descriptor() ([]byte, []int) {
	return file_speedmimi_proto_rawDescGZIP(), []int{21}
}

func (x *DisconnectBackendRequest) GetUpstream() string {
	if x != nil {
		return x.Upstream
	}
	return ""
}

func (x *DisconnectBackendRequest) GetBackendId() string {
	if x != nil {
		return x.BackendId
	}
	return ""
}

type DisconnectBackendResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *DisconnectBackendResponse) Reset() {
	*x = DisconnectBackendResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_speedmimi_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisconnectBackendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectBackendResponse) ProtoMessage() {}

func (x *DisconnectBackendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_speedmimi_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectBackendResponse.ProtoReflect.Descriptor instead.
func (*DisconnectBackendResponse) Descriptor() ([]byte, []int) {
	return file_speedmimi_proto_rawDescGZIP(), []int{22}
}

func (x *DisconnectBackendResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DisconnectBackendResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetServerStatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stats *PerformanceInfo `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
}

func (x *GetServerStatsResponse) Reset() {
	*x = GetServerStatsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_speedmimi_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetServerStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerStatsResponse) ProtoMessage() {}

func (x *GetServerStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_speedmimi_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerStatsResponse.ProtoReflect.Descriptor instead.
func (*GetServerStatsResponse) Descriptor() ([]byte, []int) {
	return file_speedmimi_proto_rawDescGZIP(), []int{23}
}

func (x *GetServerStatsResponse) GetStats() *PerformanceInfo {
	if x != nil {
		return x.Stats
	}
	return nil
}

type GetBackendStatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Upstream   string `protobuf:"bytes,1,opt,name=upstream,proto3" json:"upstream,omitempty"`
	BackendId string `protobuf:"bytes,2,opt,name=backend_id,json=backendId,proto3" json:"backend_id,omitempty"`
}

func (x *GetBackendStatsRequest) Reset() {
	*x = GetBackendStatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_speedmimi_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBackendStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackendStatsRequest) ProtoMessage() {}

func (x *GetBackendStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_speedmimi_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBackendStatsRequest.ProtoReflect.Descriptor instead.
func (*GetBackendStatsRequest) Descriptor() ([]byte, []int) {
	return file_speedmimi_proto_rawDescGZIP(), []int{24}
}

func (x *GetBackendStatsRequest) GetUpstream() string {
	if x != nil {
		return x.Upstream
	}
	return ""
}

func (x *GetBackendStatsRequest) GetBackendId() string {
	if x != nil {
		return x.BackendId
	}
	return ""
}

type GetBackendStatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stats *PerformanceInfo `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
}

func (x *GetBackendStatsResponse) Reset() {
	*x = GetBackendStatsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_speedmimi_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBackendStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBackendStatsResponse) ProtoMessage() {}

func (x *GetBackendStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_speedmimi_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBackendStatsResponse.ProtoReflect.Descriptor instead.
func (*GetBackendStatsResponse) Descriptor() ([]byte, []int) {
	return file_speedmimi_proto_rawDescGZIP(), []int{25}
}

func (x *GetBackendStatsResponse) GetStats() *PerformanceInfo {
	if x != nil {
		return x.Stats
	}
	return nil
}

type ReportPerformanceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Upstream    string           `protobuf:"bytes,1,opt,name=upstream,proto3" json:"upstream,omitempty"`
	BackendId  string           `protobuf:"bytes,2,opt,name=backend_id,json=backendId,proto3" json:"backend_id,omitempty"`
	Performance *PerformanceInfo `protobuf:"bytes,3,opt,name=performance,proto3" json:"performance,omitempty"`
}

func (x *ReportPerformanceRequest) Reset() {
	*x = ReportPerformanceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_speedmimi_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportPerformanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportPerformanceRequest) ProtoMessage() {}

func (x *ReportPerformanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_speedmimi_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportPerformanceRequest.ProtoReflect.Descriptor instead.
func (*ReportPerformanceRequest) Descriptor() ([]byte, []int) {
	return file_speedmimi_proto_rawDescGZIP(), []int{26}
}

func (x *ReportPerformanceRequest) GetUpstream() string {
	if x != nil {
		return x.Upstream
	}
	return ""
}

func (x *ReportPerformanceRequest) GetBackendId() string {
	if x != nil {
		return x.BackendId
	}
	return ""
}

func (x *ReportPerformanceRequest) GetPerformance() *PerformanceInfo {
	if x != nil {
		return x.Performance
	}
	return nil
}

type ReportPerformanceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ReportPerformanceResponse) Reset() {
	*x = ReportPerformanceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_speedmimi_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReportPerformanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportPerformanceResponse) ProtoMessage() {}

func (x *ReportPerformanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_speedmimi_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportPerformanceResponse.ProtoReflect.Descriptor instead.
func (*ReportPerformanceResponse) Descriptor() ([]byte, []int) {
	return file_speedmimi_proto_rawDescGZIP(), []int{27}
}

func (x *ReportPerformanceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReportPerformanceResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 其他必要的protobuf实现代码
var file_speedmimi_proto_rawDesc = []byte{
	// 省略具体的raw descriptor bytes，实际使用时需要包含完整的
}

var file_speedmimi_proto_rawDescGZIP = []byte{
	// 省略具体的gzip descriptor bytes，实际使用时需要包含完整的
}

var file_speedmimi_proto_msgTypes = make([]protoimpl.MessageInfo, 28)

var file_speedmimi_proto_goTypes = []any{
	(*Config)(nil),                   // 0
	(*ServerConfig)(nil),             // 1
	(*SSLConfig)(nil),                // 2
	(*BackendList)(nil),              // 3
	(*Backend)(nil),                  // 4
	(*HealthCheck)(nil),              // 5
	(*RoutingRule)(nil),              // 6
	(*GRPCConfig)(nil),               // 7
	(*PerformanceInfo)(nil),          // 8
	(*UpdateConfigRequest)(nil),      // 9
	(*UpdateConfigResponse)(nil),     // 10
	(*GetConfigResponse)(nil),        // 11
	(*ReloadSSLResponse)(nil),        // 12
	(*GetBackendsRequest)(nil),       // 13
	(*GetBackendsResponse)(nil),      // 14
	(*AddBackendRequest)(nil),        // 15
	(*AddBackendResponse)(nil),       // 16
	(*RemoveBackendRequest)(nil),     // 17
	(*RemoveBackendResponse)(nil),    // 18
	(*UpdateBackendRequest)(nil),     // 19
	(*UpdateBackendResponse)(nil),    // 20
	(*DisconnectBackendRequest)(nil), // 21
	(*DisconnectBackendResponse)(nil), // 22
	(*GetServerStatsResponse)(nil),   // 23
	(*GetBackendStatsRequest)(nil),   // 24
	(*GetBackendStatsResponse)(nil),  // 25
	(*ReportPerformanceRequest)(nil), // 26
	(*ReportPerformanceResponse)(nil), // 27
}

var file_speedmimi_proto_depIdxs = []int32{
	1,  // 0: speedmimi.Config.server:type_name -> speedmimi.ServerConfig
	2,  // 1: speedmimi.Config.ssl:type_name -> speedmimi.SSLConfig
	3,  // 2: speedmimi.Config.backends:type_name -> speedmimi.BackendList
	6,  // 3: speedmimi.Config.routing:type_name -> speedmimi.RoutingRule
	7,  // 4: speedmimi.Config.grpc:type_name -> speedmimi.GRPCConfig
	4,  // 5: speedmimi.BackendList.backends:type_name -> speedmimi.Backend
	5,  // 6: speedmimi.Backend.health_check:type_name -> speedmimi.HealthCheck
	8,  // 7: speedmimi.Backend.performance:type_name -> speedmimi.PerformanceInfo
	0,  // 8: speedmimi.UpdateConfigRequest.config:type_name -> speedmimi.Config
	0,  // 9: speedmimi.GetConfigResponse.config:type_name -> speedmimi.Config
	4,  // 10: speedmimi.GetBackendsResponse.backends:type_name -> speedmimi.Backend
	4,  // 11: speedmimi.AddBackendRequest.backend:type_name -> speedmimi.Backend
	4,  // 12: speedmimi.UpdateBackendRequest.backend:type_name -> speedmimi.Backend
	8,  // 13: speedmimi.GetServerStatsResponse.stats:type_name -> speedmimi.PerformanceInfo
	8,  // 14: speedmimi.GetBackendStatsResponse.stats:type_name -> speedmimi.PerformanceInfo
	8,  // 15: speedmimi.ReportPerformanceRequest.performance:type_name -> speedmimi.PerformanceInfo
	9,  // 16: speedmimi.ConfigService.UpdateConfig:input_type -> speedmimi.UpdateConfigRequest
	16, // 17: speedmimi.ConfigService.GetConfig:input_type -> google.protobuf.Empty
	16, // 18: speedmimi.ConfigService.ReloadSSL:input_type -> google.protobuf.Empty
	10, // 19: speedmimi.ConfigService.UpdateConfig:output_type -> speedmimi.UpdateConfigResponse
	11, // 20: speedmimi.ConfigService.GetConfig:output_type -> speedmimi.GetConfigResponse
	12, // 21: speedmimi.ConfigService.ReloadSSL:output_type -> speedmimi.ReloadSSLResponse
	13, // 22: speedmimi.BackendService.GetBackends:input_type -> speedmimi.GetBackendsRequest
	15, // 23: speedmimi.BackendService.AddBackend:input_type -> speedmimi.AddBackendRequest
	17, // 24: speedmimi.BackendService.RemoveBackend:input_type -> speedmimi.RemoveBackendRequest
	19, // 25: speedmimi.BackendService.UpdateBackend:input_type -> speedmimi.UpdateBackendRequest
	21, // 26: speedmimi.BackendService.DisconnectBackend:input_type -> speedmimi.DisconnectBackendRequest
	14, // 27: speedmimi.BackendService.GetBackends:output_type -> speedmimi.GetBackendsResponse
	18, // 28: speedmimi.BackendService.AddBackend:output_type -> speedmimi.AddBackendResponse
	20, // 29: speedmimi.BackendService.RemoveBackend:output_type -> speedmimi.RemoveBackendResponse
	22, // 30: speedmimi.BackendService.UpdateBackend:output_type -> speedmimi.UpdateBackendResponse
	24, // 31: speedmimi.BackendService.DisconnectBackend:output_type -> speedmimi.DisconnectBackendResponse
	16, // 32: speedmimi.MonitorService.GetServerStats:input_type -> google.protobuf.Empty
	25, // 33: speedmimi.MonitorService.GetBackendStats:input_type -> speedmimi.GetBackendStatsRequest
	26, // 34: speedmimi.MonitorService.ReportPerformance:input_type -> speedmimi.ReportPerformanceRequest
	23, // 35: speedmimi.MonitorService.GetServerStats:output_type -> speedmimi.GetServerStatsResponse
	27, // 36: speedmimi.MonitorService.GetBackendStats:output_type -> speedmimi.GetBackendStatsResponse
	28, // 37: speedmimi.MonitorService.ReportPerformance:output_type -> speedmimi.ReportPerformanceResponse
	19, // [19:38] is the sub-list for method output_type
	16, // [16:19] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_speedmimi_proto_init() }

func file_speedmimi_proto_init() {
	if File_speedmimi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_speedmimi_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		// 省略其他消息类型的初始化代码
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_speedmimi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_speedmimi_proto_goTypes,
		DependencyIndexes: file_speedmimi_proto_depIdxs,
		MessageInfos:      file_speedmimi_proto_msgTypes,
	}.Build()
	File_speedmimi_proto = out.File
	file_speedmimi_proto_rawDesc = nil
	file_speedmimi_proto_goTypes = nil
	file_speedmimi_proto_depIdxs = nil
}